#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Injecting apt repositories and packages ..."

DIR=/app

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ -f $DIR/apt-repositories ]; then
    apt-get update
    apt-get install -y software-properties-common
    cat "$DIR/apt-repositories" | while read repository; do
        add-apt-repository -y "\$repository"
    done
fi
if [ -f $DIR/apt-debconf ]; then
    cat "$DIR/apt-debconf" | while read conf; do
        echo \$conf | debconf-set-selections
    done
fi
if [ -f $DIR/apt-packages ]; then
    PACKAGES=\$(cat "$DIR/apt-packages" | tr "\\n" " ")
    apt-get update
    apt-get install -y \$PACKAGES
    echo "-----> Injected packages: \$PACKAGES"
fi
if [ -d $DIR/dpkg-packages ]; then
    for pkg in $DIR/dpkg-packages/*.deb; do
        dpkg -i \$pkg
        echo "-----> Injected package: \$pkg"
    done
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
